import React, { useState, useEffect, useMemo } from "react";
import { supabase } from "@/api/supabaseClient";
import { useNavigate } from "react-router-dom";
import { ChevronLeft, ChevronRight, Star, ClipboardList, Copy, X, Check, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import BottomTabs from "@/components/showpilot/BottomTabs";
import StatusBadge from "@/components/showpilot/StatusBadge";
import moment from "moment";

function getShowAccentColor(show) {
  if (show.is_linked) return "#F472B6"; // pink for linked gigs
  if (show.starred) return "#FBBF24"; // amber for starred
  if (show.status === "complete") return "#8CFF3D"; // green for worked
  if (show.status === "in_progress") return "#60A5FA"; // blue for frequent/in-progress
  return "#555"; // grey for never worked
}

export default function CalendarPage() {
  const [shows, setShows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [currentMonth, setCurrentMonth] = useState(moment());
  const [tmCopied, setTmCopied] = useState(false);
  const [tmLink, setTmLink] = useState(null);
  const [generatingLink, setGeneratingLink] = useState(false);
  const [dayModalKey, setDayModalKey] = useState(null);
  const [selectedDate, setSelectedDate] = useState(null);
  const navigate = useNavigate();

  const handleTourManagerLink = async () => {
    setGeneratingLink(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Not logged in");

      const { data: prefs } = await supabase
        .from("user_preferences")
        .select("display_name")
        .eq("user_id", user.id)
        .maybeSingle();

      const engineerName = prefs?.display_name || user.user_metadata?.full_name || user.user_metadata?.name || user.email || "";

      const { data: request, error } = await supabase
        .from("tour_manager_requests")
        .insert({
          engineer_user_id: user.id,
          engineer_name: engineerName,
          status: "pending",
          // invite_token is auto-generated by the database (default gen_random_uuid())
        })
        .select()
        .single();

      if (error) throw error;

      const name = encodeURIComponent(engineerName || "your engineer");
      const url = `${window.location.origin}/tm-intake?token=${request.invite_token}&engineer=${user.id}&name=${name}&email=${encodeURIComponent(user.email || "")}`;
      setTmLink(url);
    } catch (e) {
      console.error(e);
    }
    setGeneratingLink(false);
  };

  const handleCopyLink = () => {
    if (tmLink) {
      navigator.clipboard.writeText(tmLink).catch(() => {});
      setTmCopied(true);
      setTimeout(() => setTmCopied(false), 1500);
    }
  };

  const handleShareMore = async () => {
    if (!tmLink) return;
    setTmLink(null);
    if (navigator.share) {
      try {
        await navigator.share({ title: "Performer Intake Link", url: tmLink });
      } catch (e) {
        // user cancelled the native share sheet — nothing to do
      }
    }
  };

  useEffect(() => {
    let isMounted = true;

    async function loadShows() {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        if (isMounted) setLoading(false);
        return;
      }

      const { data, error } = await supabase
        .from("shows")
        .select("*")
        .eq("owner_id", user.id)
        .order("date", { ascending: false });

      let ownShows = error ? [] : (data || []);
      if (error) console.error("Error loading shows:", error);

      const { data: links } = await supabase
        .from("linked_gigs")
        .select("share_token")
        .eq("user_id", user.id)
        .eq("archived", false);

      if (links && links.length > 0) {
        const linkedDetails = await Promise.all(
          links.map(async (link) => {
            const { data: g } = await supabase.rpc("get_shared_gig", { p_token: link.share_token });
            return g ? { ...g, is_linked: true, share_token: link.share_token } : null;
          })
        );
        ownShows = [...ownShows, ...linkedDetails.filter(Boolean)];
      }

      if (isMounted) setShows(ownShows);
      if (isMounted) setLoading(false);
    }

    loadShows();
    return () => { isMounted = false; };
  }, []);

  const showsByDate = useMemo(() => {
    const map = {};
    shows.forEach((s) => {
      if (s.date) {
        if (!map[s.date]) map[s.date] = [];
        map[s.date].push(s);
      }
    });
    return map;
  }, [shows]);

  const daysInMonth = useMemo(() => {
    const start = currentMonth.clone().startOf("month").startOf("week");
    const end = currentMonth.clone().endOf("month").endOf("week");
    const days = [];
    const d = start.clone();
    while (d.isSameOrBefore(end)) {
      days.push(d.clone());
      d.add(1, "day");
    }
    return days;
  }, [currentMonth]);

  const openShow = (show) => {
    if (show.is_linked) {
      navigate(`/gig/shared?token=${show.share_token}`);
    } else {
      navigate(`/show/${show.id}`, { state: { from: "calendar" } });
    }
  };

  // Lets the calendar create a new show pre-filled with a specific date,
  // so multiple shows can be added to the same day directly from here.
  const newShowOnDate = (dateKey) => {
    navigate("/show/new", { state: { from: "calendar", prefillDate: dateKey } });
  };

  return (
    <div className="min-h-screen bg-[#0d0d0d] pb-24">
      {/* Manager Import Link share menu */}
      {tmLink && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 px-4 h-[100dvh]" onClick={() => setTmLink(null)}>
          <div className="bg-[#161616] border border-[#2a2a2a] rounded-2xl p-2 w-full max-w-sm" onClick={(e) => e.stopPropagation()}>
            <div className="px-3 pt-3 pb-2">
              <h3 className="text-white font-bold text-base">Performer Intake</h3>
              <p className="text-white/40 text-xs mt-0.5">Share this with a performer. They'll fill out their act's info and it'll appear on your profile.</p>
            </div>
            <button onClick={handleCopyLink} className="w-full flex items-center gap-3 px-4 py-3.5 rounded-xl hover:bg-white/5 text-left">
              {tmCopied ? <Check className="w-4 h-4 text-[#8CFF3D]" /> : <Copy className="w-4 h-4 text-[#8CFF3D]" />}
              <span className="text-white text-sm font-medium">{tmCopied ? "Copied!" : "Copy Link"}</span>
            </button>
            {typeof navigator !== "undefined" && navigator.share && (
              <button onClick={handleShareMore} className="w-full flex items-center gap-3 px-4 py-3.5 rounded-xl hover:bg-white/5 text-left">
                <Copy className="w-4 h-4 text-white/60" />
                <span className="text-white text-sm font-medium">More Options...</span>
              </button>
            )}
            <button onClick={() => setTmLink(null)} className="w-full text-center py-3 mt-1 text-white/40 hover:text-white text-sm border-t border-[#2a2a2a]">
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Day list modal — shows every gig on a given date, with a way to add another */}
      {dayModalKey && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 px-4" onClick={() => setDayModalKey(null)}>
          <div className="bg-[#161616] border border-[#2a2a2a] rounded-2xl p-5 w-full max-w-md max-h-[80vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-white font-bold text-base">{moment(dayModalKey).format("MMMM D, YYYY")}</h3>
              <button onClick={() => setDayModalKey(null)} className="text-white/40 hover:text-white">
                <X className="w-5 h-5" />
              </button>
            </div>
            <div className="space-y-2 mb-3">
              {(showsByDate[dayModalKey] || []).map((s) => {
                const color = getShowAccentColor(s);
                return (
                  <button key={s.id} onClick={() => openShow(s)} className="w-full text-left">
                    <div className="bg-[#111] rounded-xl border border-[#222] p-3 flex items-center gap-3 hover:bg-[#1a1a1a] transition-colors">
                      <div className="w-1 h-8 rounded-full" style={{ backgroundColor: color }} />
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-1.5">
                          <p className="text-white font-medium text-sm truncate">{s.band_name || s.event_name || "Untitled Gig"}</p>
                          {s.starred && <Star className="w-3 h-3 text-amber-400 shrink-0" fill="currentColor" />}
                        </div>
                        {s.venue && <p className="text-white/40 text-xs truncate">{s.venue}</p>}
                      </div>
                      <StatusBadge status={s.status} />
                    </div>
                  </button>
                );
              })}
            </div>
            <Button onClick={() => newShowOnDate(dayModalKey)} className="w-full bg-[#8CFF3D] text-black hover:bg-[#7ae62e] font-semibold rounded-xl">
              + Add another show
            </Button>
          </div>
        </div>
      )}

      <div className="sticky top-0 z-40 bg-[#0d0d0d]/95 backdrop-blur-lg border-b border-[#1a1a1a]">
        <div className="flex items-center justify-between px-4 py-3 max-w-lg mx-auto">
          <Button variant="ghost" size="sm" onClick={() => setCurrentMonth((m) => m.clone().subtract(1, "month"))} className="text-white/50 hover:text-white h-8 w-8 p-0">
            <ChevronLeft className="w-5 h-5" />
          </Button>
          <h2 className="text-lg font-bold text-white">{currentMonth.format("MMMM YYYY")}</h2>
          <Button variant="ghost" size="sm" onClick={() => setCurrentMonth((m) => m.clone().add(1, "month"))} className="text-white/50 hover:text-white h-8 w-8 p-0">
            <ChevronRight className="w-5 h-5" />
          </Button>
        </div>

        {/* Legend */}
        <div className="flex items-center gap-3 px-4 pb-3 max-w-lg mx-auto text-[10px] text-white/40 flex-wrap">
          <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-[#555]" />New</span>
          <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-blue-400" />Frequent</span>
          <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-[#8CFF3D]" />Worked</span>
          <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-amber-400" />Starred</span>
          <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full" style={{ backgroundColor: "#F472B6" }} />Linked</span>
        </div>
      </div>

      <div className="px-4 pt-4 max-w-lg mx-auto">
        {loading ? (
          <div className="flex justify-center py-20">
            <div className="w-6 h-6 border-2 border-[#8CFF3D]/30 border-t-[#8CFF3D] rounded-full animate-spin" />
          </div>
        ) : (
          <div>
            <div className="grid grid-cols-7 gap-1.5 mb-2">
              {["S","M","T","W","T","F","S"].map((d, i) => (
                <div key={i} className="text-center text-sm text-white/30 font-medium py-1">{d}</div>
              ))}
            </div>
            <div className="grid grid-cols-7 gap-1.5">
              {daysInMonth.map((day) => {
                const key = day.format("YYYY-MM-DD");
                const dayShows = showsByDate[key] || [];
                const isCurrentMonth = day.isSame(currentMonth, "month");
                const isToday = day.isSame(moment(), "day");
                const hasShows = dayShows.length > 0;

                return (
                  <div
                    key={key}
                    onClick={() => {
                      if (!isCurrentMonth) return;
                      if (selectedDate === key) {
                        if (hasShows) setDayModalKey(key);
                        else newShowOnDate(key);
                      } else {
                        setSelectedDate(key);
                      }
                    }}
                    className={`relative rounded-xl overflow-hidden transition-colors ${isCurrentMonth ? "bg-[#161616] cursor-pointer hover:bg-[#1c1c1c]" : "bg-transparent"} ${selectedDate === key ? "ring-2 ring-[#8CFF3D]" : ""}`}
                    style={{ minHeight: hasShows ? "92px" : "68px" }}
                  >
                    <div className="px-1.5 pt-1.5">
                      <span className={`text-sm font-medium ${isToday ? "text-[#8CFF3D] font-bold" : isCurrentMonth ? "text-white/60" : "text-white/15"}`}>
                        {day.date()}
                      </span>
                    </div>
                    {dayShows.slice(0, 2).map((s) => {
                      const color = getShowAccentColor(s);
                      return (
                        <div key={s.id} className="w-full mt-1 px-1.5 pb-0.5">
                          <div className="rounded-md px-1.5 py-1 text-left" style={{ backgroundColor: color + "22", borderLeft: `2px solid ${color}` }}>
                            <p className="text-[11px] font-medium leading-tight truncate" style={{ color }}>
                              {s.band_name || s.event_name || "Untitled Gig"}
                            </p>
                            {s.venue && <p className="text-[10px] text-white/30 truncate leading-tight">{s.venue}</p>}
                          </div>
                        </div>
                      );
                    })}
                    {dayShows.length > 2 && (
                      <p className="w-full px-1.5 pb-1 text-[10px] text-white/30 text-center">
                        +{dayShows.length - 2} more
                      </p>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>

      <div className="px-4 pt-4 pb-2 max-w-lg mx-auto">
        <Button onClick={handleTourManagerLink} disabled={generatingLink} className="w-full font-semibold rounded-xl" style={{ backgroundColor: "#a855f7", color: "#fff" }}>
          <ClipboardList className="w-4 h-4 mr-2" />
          {generatingLink ? "Generating..." : "Create import link"}
        </Button>
      </div>

      <BottomTabs />
    </div>
  );
}
